version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"

  web:
    build: .
    container_name: flask_app
    environment:
      DATABASE_URL: postgres://user:password@db:5432/testdb
    ports:
      - "5000:5000"
    depends_on:
      - db
    command: python app.py